### ISSUE TITLE
Mod didn't fully install

### ISSUE THREAD

**Issue by placekicker217** [cfbrevamped/CFBR-Easy-Installer#271]
So, I just downloaded the college football revamped ESPN digital file. From what I've seen, some of the mod installed, but some didn't. For example, the names of the new teams did, but the teams that they replaced remained the same. For example, Costal Carolina replaced New Mexico State. But, the team wore the New Mexico St uniform with the Coastal Carolina helmet. On the play call screen, the new ESPN logo is present, but the choose your play box is the old one. Also, all of the logos on the team selection screen are the old ones. 

Did I do something wrong when I installed it? Any help is appreciated.

**Comment by placekicker217** [comment]
Another thing I found was with the alternate helmets of some of the teams. Ole Miss’ powder blue one didn’t load. And with Oregon, I chose the black helmet with the yellow O, and when the game opened, my team had the white helmet with the silver wings. 

Should I try to download the mod again and re-install it? My observations happened with the espn and legacy scorebugs. I tried both. It took a while to download for me, so I’m wondering if something happened to the files with that. 

Again, this is so freaking cool. Thanks for all of your hard work!

**Comment by placekicker217** [comment]
Ok. So I messed around with it today and finally got it to work. I had made two errors. First, I didn’t have the fame file in the right folder. Then, I downloaded the wrong version of the mod. Once I fixed those two issues, it worked like a charm. I am so impressed by yalls work! I was smiling from ear to ear playing my first game. Strong work! 

On behalf of the college football community, I can’t say thank you enough!!!

**Comment by saucy351** [comment]
> Ok. So I messed around with it today and finally got it to work. I had made two errors. First, I didn’t have the fame file in the right folder. Then, I downloaded the wrong version of the mod. Once I fixed those two issues, it worked like a charm. I am so impressed by yalls work! I was smiling from ear to ear playing my first game. Strong work!
> 
> On behalf of the college football community, I can’t say thank you enough!!!

Where do I find this file and to make sure they are in the right folder?
I have the new scorebug on PC and logos dont show on the scoreboard and also I have the old plays and some uniform issues like you

**Comment by placekicker217** [comment]
OK, so the PS3 emulator has a lot of folders. Find the one marked dev_hdd0. There should be a folder marked disc inside of that one. If not, make one. Inside the disc folder, make a folder titled exactly this -BLUS31159-[NCAA Football 14]. Put the game in this one. Then, put the mod in the emulator by dragging and dropping. Click ok to install the files. This should make it work for you.

**Comment by saucy351** [comment]
I did that but still get the older setup screen and loading I don’t have the revamped screens

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
